### PR TITLE
Fix build with orc

### PR DESCRIPTION
**Pull request by kleisauke**
Regressed since 71d356b.

See: https://github.com/libvips/libvips/actions/runs/11304572685/job/31443113383

<details>
  <summary>Details</summary>

```
In file included from /usr/include/orc-0.4/orc/orcprogram.h:7,
                 from /usr/include/orc-0.4/orc/orc.h:6,
                 from ../libvips/resample/reducev.cpp:80:
/usr/include/orc-0.4/orc/orcexecutor.h:42:8: error: redefinition of ‘struct _OrcExecutor’
   42 | struct _OrcExecutor {
      |        ^~~~~~~~~~~~
In file included from ../libvips/include/vips/vips.h:139,
                 from ../libvips/resample/reducev.cpp:71:
../libvips/include/vips/vips7compat.h:1665:16: note: previous definition of ‘struct _OrcExecutor’
 1665 | typedef struct _OrcExecutor {
      |                ^~~~~~~~~~~~
In file included from /usr/include/orc-0.4/orc/orc.h:6,
                 from ../libvips/resample/reducev.cpp:80:
/usr/include/orc-0.4/orc/orcprogram.h:27:8: error: redefinition of ‘struct _OrcProgram’
   27 | struct _OrcProgram {
      |        ^~~~~~~~~~~
In file included from ../libvips/include/vips/vips.h:139,
                 from ../libvips/resample/reducev.cpp:71:
../libvips/include/vips/vips7compat.h:1661:16: note: previous definition of ‘struct _OrcProgram’
 1661 | typedef struct _OrcProgram {
      |                ^~~~~~~~~~~
```
</details>

### CODE REVIEW

**Comment by kleisauke** [comment]
The initial revision of this PR would break ABI/API compat, see:
https://kleisauke.nl/compat_reports/vips/8.15.5-rc1_to_fix-build-with-orc/compat_report.html#SourceTab

So, changed to just `#ifndef` instead.
https://kleisauke.nl/compat_reports/vips/8.15.5-rc1_to_fix-build-with-orc-rev2/compat_report.html#SourceTab
