### ISSUE TITLE
vips failed to build with --without-lcms

### ISSUE THREAD

**Issue by speckins** [libvips/libvips#53]
vips 7.32.0 is failing to build without lcms with some undefined references to vips_icc_\* functions.  It works in 7.30.8.

```
$ ./configure --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --without-lcms && CFLAGS="-march=core2 -O2 -pipe" make -j9
(...lots of output snipped...)
g-ir-scanner: compile: gcc -Wall -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -g -O2 -I../libvips/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -c -o /tmp/vips-7.32.0/libvips/tmp-introspectU_Biy_/Vips-8.0.o /tmp/vips-7.32.0/libvips/tmp-introspectU_Biy_/Vips-8.0.c
g-ir-scanner: link: /bin/sh ../libtool --mode=link --tag=CC gcc -o /tmp/vips-7.32.0/libvips/tmp-introspectU_Biy_/Vips-8.0 -export-dynamic -g -O2 /tmp/vips-7.32.0/libvips/tmp-introspectU_Biy_/Vips-8.0.o -L. libvips.la -lgio-2.0 -lgobject-2.0 -Wl,--export-dynamic -lgmodule-2.0 -pthread -lrt -lglib-2.0
libtool: link: gcc -o /tmp/vips-7.32.0/libvips/tmp-introspectU_Biy_/.libs/Vips-8.0 -g -O2 /tmp/vips-7.32.0/libvips/tmp-introspectU_Biy_/Vips-8.0.o -Wl,--export-dynamic -pthread -Wl,--export-dynamic  -L. ./.libs/libvips.so -lgio-2.0 -lgobject-2.0 -lgmodule-2.0 -lrt -lglib-2.0 -fopenmp -pthread
./.libs/libvips.so: undefined reference to `vips_icc_transform'
./.libs/libvips.so: undefined reference to `vips_icc_ac2rc'
./.libs/libvips.so: undefined reference to `vips_icc_export'
./.libs/libvips.so: undefined reference to `vips_icc_import'
collect2: ld returned 1 exit status
linking of temporary binary failed: Command '['/bin/sh', '../libtool', '--mode=link', '--tag=CC', 'gcc', '-o', '/tmp/vips-7.32.0/libvips/tmp-introspectU_Biy_/Vips-8.0', '-export-dynamic', '-g', '-O2', '/tmp/vips-7.32.0/libvips/tmp-introspectU_Biy_/Vips-8.0.o', '-L.', 'libvips.la', '-lgio-2.0', '-lgobject-2.0', '-Wl,--export-dynamic', '-lgmodule-2.0', '-pthread', '-lrt', '-lglib-2.0']' returned non-zero exit status 1
make[3]: *** [Vips-8.0.gir] Error 1
make[3]: Leaving directory `/tmp/vips-7.32.0/libvips'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/tmp/vips-7.32.0/libvips'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/vips-7.32.0'
make: *** [all] Error 2
```
