### ISSUE TITLE
'make' tries to execute commented out lines and fails

### ISSUE THREAD

**Issue by uddeep-juturu** [libvips/libvips#1429]
After configure and i was trying to make and it fails with "No such file or directory", where it tries to include a nonexisting file.
Unfortunately, those include lines are commented out in vips-8.8.2/libvips/foreign/magick.h
Any idea why is this happening? and how to fix this?

```
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../.. -I../../libvips/include -DG_DISABLE_ASSERT -DG_DISABLE_CHECKS -pthread -fopenmp -I/usr/lib64/glib-2.0/include -I/usr/include/libxml2 -I/usr/include/libpng15 -I/usr/include/glib-2.0 -I/data/include/libgsf-1 -I/data/include/ImageMagick-7 -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_HDRI_ENABLE=0 -g -O2 -MT magick.lo -MD -MP -MF .deps/magick.Tpo -c magick.c  -fPIC -DPIC -o .libs/magick.o
In file included from magick.c:49:0:
magick.h:41:35: fatal error: MagickCore/MagickCore.h: No such file or directory
 #include <MagickCore/MagickCore.h>



[root@0d50670b2b38 foreign]# pwd
/data/vips-8.8.2/libvips/foreign
[root@0d50670b2b38 foreign]# more magick.h
#if defined(HAVE_MAGICK6) || defined (HAVE_MAGICK7)

#ifdef HAVE_MAGICK6
#include <magick/api.h>
#define MaxPathExtent MaxTextExtent
#endif /*HAVE_MAGICK6*/

#ifdef HAVE_MAGICK7
#include <MagickCore/MagickCore.h>
#define MaxPathExtent MagickPathExtent
#endif /*HAVE_MAGICK7*/

Image *magick_acquire_image( const ImageInfo *image_info,
        ExceptionInfo *exception );
```

**Comment by jcupitt** [comment]
Hello, this is was fixed in 8.8.3, try that:

https://github.com/libvips/libvips/releases/tag/v8.8.3

**Comment by uddeepjuturu** [comment]
Hello John,
Thanks for the quick reply but unfortunately, its the same issue with v8.8.3.

```
[In file included from magick.c:49:0:
magick.h:41:35: fatal error: MagickCore/MagickCore.h: No such file or directory
 #include <MagickCore/MagickCore.h>
                                   ^
compilation terminated.
make[3]: *** [magick.lo] Error 1
make[3]: Leaving directory `/data/vips-8.8.3/libvips/foreign'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/data/vips-8.8.3/libvips'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/data/vips-8.8.3'
make: *** [all] Error 2](url)

```

**Comment by jcupitt** [comment]
Huh strange. Do you know what version of imagemagick are you building against?

**Comment by jcupitt** [comment]
So my guess would be that you have a broken ImageMagick install. Could you post the output of `configure`?

**Comment by uddeep-juturu** [comment]
Hello John, 
I'm trying to install vips against Imagemagick 7.0.8 (latest).
After i copied the MagickCore from Imagemagick to vips-8.8.2/libvips/foreign/MagickCore/, It is able to proceed further now.


```
rsync -avzh ${HOME}/ImageMagick-7.0.8-64/MagickCore/ ${HOME}/vips-8.8.2/libvips/foreign/MagickCore/
```

**Comment by jcupitt** [comment]
Please don't do that! You'll break things and make it very difficult to fix. I would remove that directory.

It works fine with IM 7.0.8 here, you must have some problem with the way you have installed ImageMagick. 

So ... what platform are you using, how did you install imagemagick, and what output did you get for libvips `configure`.

**Comment by uddeep-juturu** [comment]
My goal is to package vips (on a temp container), to be able to use on any node together with imagemagick.
I did a configure/make/make-install of imagemagic-7 and copied the lib and inlude to /opt/vips.
And configure/make/make-install of libvips to /opt/vips and then packaged it.
Here is the configure of libvips.

```
* build options
native win32:				no
native OS X:				no
open files in binary mode: 		no
enable debug:				no
enable deprecated library components:	yes
enable docs with gtkdoc:		no
gobject introspection: 			no
enable radiance support: 		yes
enable analyze support: 		yes
enable PPM support: 			yes

* optional dependencies
use fftw3 for FFT: 			no
Magick package: 			MagickCore
Magick API version: 			magick7
load with libMagick: 			yes
save with libMagick: 			yes
accelerate loops with orc: 		no
  (requires orc-0.4.11 or later)
ICC profile support with lcms: 		no
file import with niftiio: 		no
file import with libheif: 		no
file import with OpenEXR: 		no
file import with OpenSlide:		no
  (requires openslide-3.3.0 or later)
file import with matio: 		no
PDF import with PDFium 			no
PDF import with poppler-glib: 		no
  (requires poppler-glib 0.16.0 or later)
SVG import with librsvg-2.0: 		no
  (requires librsvg-2.0 2.34.0 or later)
zlib: 					yes
file import with cfitsio: 		no
file import/export with libwebp:	no
  (requires libwebp, libwebpmux, libwebpdemux 0.5.0 or later)
text rendering with pangoft2: 		no
file import/export with libpng: 	yes (pkg-config libpng >= 1.2.9)
  (requires libpng-1.2.9 or later)
support 8bpp PNG quantisation:		no
  (requires libimagequant)
file import/export with libtiff:	yes (pkg-config libtiff-4)
file import/export with giflib:		no
file import/export with libjpeg:	yes (pkg-config)
image pyramid export:			yes
  (requires libgsf-1 1.14.26 or later)
use libexif to load/save JPEG metadata: yes
```

**Comment by jcupitt** [comment]
I don't think that will work. You can't just copy libs and headers about on linux systems unless they have been carefully designed to be relocatable.

Instead, you need to build your stack of packages to the same prefix.  For example:

https://github.com/jcupitt/docker-builds/blob/master/libvips-openjpeg-alpine/Dockerfile

Builds openjpeg, imagemagick and libvips to `/usr/local`. You'd need to set the prefix to `/opt/vips` instead.

**Comment by uddeep-juturu** [comment]
Thanks for the input John.. Will work on this.
